In [12]:
#Import scikit-learn dataset library
from sklearn import datasets

#Load dataset
cancer = datasets.load_breast_cancer()

In [13]:
# print the names of the 13 features
print("Features: ", cancer.feature_names)

# print the label type of cancer('malignant' 'benign')
print("Labels: ", cancer.target_names)

Features:  ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
Labels:  ['malignant' 'benign']


In [95]:
data = np.loadtxt("test.txt", delimiter=" ")
ntarget = [0 if sum(val) >2 else 1 for val in data]
mtarget = np.asarray(ntarget)

for n in zip(data,mtarget):
    print(n[0],n[1])

print(len(mtarget), len(data))
print(mtarget.shape, data.shape)

[0.01641181 1.         0.         0.01654354 0.0164113  0.01641181] 1
[0.01040749 1.         0.         0.01045824 0.01040738 0.01040749] 1
[0.01286201 1.         0.         0.01294046 0.01286178 0.01286201] 1
[0.00523526 1.         0.         0.0052497  0.00523524 0.00523526] 1
[0.00514016 1.         0.         0.00515043 0.00514015 0.00514016] 1
[0.98237287 0.         1.         0.98221688 0.98237355 0.98237287] 0
[0.00830975 1.         0.         0.00834316 0.00830969 0.00830975] 1
[0.99607814 0.         1.         0.9960707  0.99607815 0.99607814] 0
[0.00739276 1.         0.         0.00741469 0.00739275 0.00739276] 1
[0.98949054 0.97873057 0.         1.         0.98944866 0.9894906 ] 0
[0.98675217 0.         1.         0.98666873 0.98675242 0.98675217] 0
[0.98737692 0.         1.         0.98729997 0.98737715 0.98737692] 0
[0.98537774 0.         1.         0.98527964 0.98537805 0.98537774] 0
[0.98394707 0.         1.         0.98381864 0.98394758 0.98394707] 0
[0.97958586 0.      

In [96]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(data, mtarget, test_size=.7,random_state=55) # 70% training and 30% test

In [97]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='rbf') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [98]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 1.0


In [99]:
# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:",metrics.precision_score(y_test, y_pred))

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:",metrics.recall_score(y_test, y_pred))

Precision: 1.0
Recall: 1.0


In [101]:
a = np.array([0.94675123,0.,1.,0.98531873,0.97675242,0.98675217]).reshape(1, -1)
print(a)
print(clf.predict(a))

b = data[1].reshape(1, -1)
print(b)
print(clf.predict(b))


[[0.94675123 0.         1.         0.98531873 0.97675242 0.98675217]]
[0]
[[0.01040749 1.         0.         0.01045824 0.01040738 0.01040749]]
[1]
